version: '3.9'

services:
  backend:
    image: enki-backend:latest
    build: ./backend
    container_name: enki-backend
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://enki-postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    depends_on:
      - enki-postgres
    networks:
      - enki-net

  frontend:
    build: ./frontend
    container_name: enki-frontend
    ports:
      - '4200:80'
    networks:
      - enki-net

  enki-postgres:
    image: postgres:latest
    container_name: enki-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - enki-net

networks:
  enki-net:

volumes:
  pgdata:
