version: '3.9'

services:
enki-backend:
    image: 'enki-backend:latest'
    build: ./backend
    container_name: enki-backend
    ports:
      - '8080:8080'
    environment:
      SPRING_DATA_POSTGRESQL_URL: 'jdbc:postgresql://postgres:5432/mydatabase'
      SPRING_DATA_POSTGRESQL_USERNAME: 'myuser'
      SPRING_DATA_POSTGRESQL_PASSWORD: 'secret'
      SPRING_JPA_HIBERNATE_DDL_AUTO: 'update'
    depends_on:
      - enki-postgres
    networks:
      - enki-net

enki-frontend:
  build: ./frontend
  container_name: enki-frontend
  ports: '5432:5432'
  networks: enki-net
  environment:
    postgres_db: mydatabase
    postgres_user: myuser
    postgres_password: secret
  volumes:
    - pgdata: /var/lib/postgresql/data
  
enki-networks:
  - enki-net
volumes:
  pgdata: